import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Link from "next/link";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main className={`${styles.main}`}>
				<Link href={"/ExampleOne"} className={styles.link}>
					Example 1
				</Link>
				<Link href={"/ExampleTwo"} className={styles.link}>
					Example 2
				</Link>
				<Link href={"/ExampleThree"} className={styles.link}>
					Example 3
				</Link>
				<Link href={"/ExampleFour"} className={styles.link}>
					Example 4
				</Link>
				<Link href={"/ExampleFive"} className={styles.link}>
					Example 5
				</Link>
			</main>
			<Footer />
		</>
	);
}
